### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by chrissimpkins** [google/zopfli#142]
There are a number of commits to master since the October 2015 release of v1.0.1 at https://github.com/google/zopfli/commit/89cf773beef75d7f4d6d378debdf299378c3314e.  If these changes are stable / production-ready, would it be possible to tag a new release?  Thanks much!

**Comment by lvandeve** [comment]
Thank you for pointing out, it's indeed stable, and now tagged as zopfli-1.0.2
https://github.com/google/zopfli/releases/tag/zopfli-1.0.2
