### ISSUE TITLE
zopflipng not found on Ubuntu 16.04 xenial

### ISSUE THREAD

**Issue by Utkarsh1308** [google/zopfli#161]
On running the command 
`sudo apt-get install zopfli`

Only zopfli seems to be getting installed. zopflipng command is not found. 

I tested the same on ubuntu 18.04 and there it seems to work fine.

**Comment by CounterPillow** [comment]
This is not the issue of upstream zopfli but your distribution's packager, i.e. Ubuntu. There is no point in reporting this here, as nobody here can do anything about it.

**Comment by Utkarsh1308** [comment]
Is there any way to install zopflipng using terminal in ubuntu 16.04 ? Actually I need zopflipng to run some tests o travis

**Comment by CounterPillow** [comment]
```
git clone https://github.com/google/zopfli.git
cd zopfli
make zopflipng
install -Dm755 zopflipng /usr/local/bin/zopflipng
```
