### ISSUE TITLE
Compile error: divide or mod by zero in lodepng

### ISSUE THREAD

**Issue by EwoutH** [google/zopfli#162]
https://github.com/Mattlk13/zopfli/pull/3 introduced a compile error on `zopfli\src\zopflipng\lodepng\lodepng_util.cpp`, throwing an _error C2124: divide or mod by zero_. See this [AppVeyor build](https://ci.appveyor.com/project/EwoutH/zopfli/builds/28314865/job/gleoaigmr54jktu5) as an example.
```
(ClCompile target) -> 
  C:\projects\zopfli\src\zopflipng\lodepng\lodepng_util.cpp(299,1): error C2124: divide or mod by zero [C:\projects\zopfli\cmake_build\libzopflipng.vcxproj]
    69 Warning(s)
    1 Error(s)
```
There are also a lot of [open warnings](https://gist.github.com/EwoutH/3ea4750455a3a33967c8cd94d3d68372) that should be addressed.

**Comment by jibsen** [comment]
For reference; https://github.com/lvandeve/lodepng/issues/109

**Comment by lvandeve** [comment]
I updated lodepng again in commit 2f940d2b0b2a2894766d220785a435fd58d11679, does this fix it it for you?

Thank you

**Comment by EwoutH** [comment]
Unfortunately it did not: https://ci.appveyor.com/project/EwoutH/zopfli/builds/28410278/job/47laf4tngkfpjdpp

**Comment by zvezdochiot** [comment]
https://github.com/lvandeve/lodepng/issues/109

**Comment by lvandeve** [comment]
@EwoutH thanks for the second link. It shows an error on line 306:

"C:\projects\zopfli\src\zopflipng\lodepng\lodepng_util.cpp(306,1): error C2124: divide or mod by zero [C:\projects\zopfli\cmake_build\libzopflipng.vcxproj]"

But I have on line 306 the following, so it's odd that it gives a division through zero error for that particular line (and not earlier ones)

"return (x < -lodepng_flt_max) ? (y < 0 ? 0 : lodepng_flt_inf) :"

Can you please verify what you see on line 306?

Thank you

**Comment by EwoutH** [comment]
@lvandeve [The same](https://github.com/EwoutH/zopfli/blob/patch-3/src/zopflipng/lodepng/lodepng_util.cpp#L306) I'm afraid.

`          return (x < -lodepng_flt_max) ? (y < 0 ? 0 : lodepng_flt_inf) :`

**Comment by lvandeve** [comment]
@EwoutH would you be willing to experiment a bit, such as temporarily commenting out this line, or even temporarily letting the function lodepng_powf return 0 and remove all the rest, or something else that could temporarily fix it (at least temporarily remove the compiler error, to pinpoint what exactly it's giving the error for)?

The actual division through zero after commit 2f940d2 is on lines 286 and 287.

I haven't got this compiler available, and g++/clang++ don't give this error, so it would be very helpful to diagnose the problem that way.

Thank you :)

**Comment by lvandeve** [comment]
One more idea to try: remove "static const" from lodepng_flt_zero_" on line 285, or, remove "static const" from all three lines there.

**Comment by EwoutH** [comment]
@lvandeve Yes, replacing `static const float` by `float` on line 285 solves [the division error](https://ci.appveyor.com/project/EwoutH/zopfli/builds/28443246/job/9roq00mpxwl0s85v) and makes it compile correctly!

There are still about 70 warnings though, including a lot in lodepng.

**Comment by zvezdochiot** [comment]
@EwoutH say:
>There are still about 70 warnings though, including a lot in lodepng.

https://pastebin.com/

**Comment by lvandeve** [comment]
The referenced commit should fix the error.

Thanks for the warning log, that's independent from this issue, closing since it should be fixed
