### ISSUE TITLE
1.0.1 Release?

### ISSUE THREAD

**Issue by seamlik** [google/zopfli#76]
I can see there have been quite a few changes since 1.0.0 release. Now that 2 years have past, why not make a 1.0.1 release yet, as the Makefile implies?

**Comment by lvandeve** [comment]
Made a tag zopfli-1.0.1.

Out of interest, what is the reason for needing this?

**Comment by seamlik** [comment]
Surprised that you simply added the tag...

I am an Debian maintainer and some of our packages need the libraries zopfli-1.0.1 produces but zopfli-1.0.0 does not. On the other hand, you have also fixed bugs and added features since 1.0.0 release. Since we can't package an unreleased version of a software, we asked if you are going to make a new release.

**Comment by lvandeve** [comment]
Is there anything I can do to make life easier for you? Did this tag made things better or worse? Feedback is welcome, thanks :)

**Comment by JoshStrobl** [comment]
@lvandeve While I don't speak for @seamlik, I do the package maintaining of zopli for [Solus](https://solus-project.com) and the tagging made things much easier. Thanks!

**Comment by Sampsca** [comment]
What are the chances we can get precompiled binaries and libraries with each major release?

**Comment by CounterPillow** [comment]
@Sampsca All this requires to build is a C compiler and GNU make. I don't think it's worth the effort to release precompiled builds when it compiles that easily on all major platforms without any dependencies.

**Comment by Sampsca** [comment]
@CounterPillow 
I disagree.  The stated design goal/purpose of zopflipng is: "By releasing this software we hope to make images on the web load faster without a new image format."  In order for this design goal to be fulfilled, people actually have to use zopflipng on their PNGs.  In my experience, people who are not already (C/C++) programmers are rarely willing to go to the trouble of installing compilers and figuring out how to use them, even if the process is considered easy by those people who already know how to compile.  Faced with the prospect of having to compile a program themselves, most non-programmers will either find alternative software which is already compiled and ready to use, or will simply do without.  By not providing compiled versions of zopfli and zopflipng, the developers are missing the opportunity to reach a large portion of their target audience, and therefore fall short of optimizing the effectiveness of their design goal.  Virtually all of the competitors to zopflipng are provided as or include compiled binaries, but zopflipng tends to provide the best compression.

**Comment by CounterPillow** [comment]
@Sampsca 
>Faced with the prospect of having to compile a program themselves, most non-programmers will either find alternative software which is already compiled and ready to use, or will simply do without.

Or they could use a binary distribution which ships zopflipng; distribution is a problem to be solved by distributions; Having upstream packages for each major distribution is a lot of effort to set up.

For Windows, you may have a point (even though this is a command line utility so, eeeh, it's not exactly user friendly for beginners in the first place), but making builds for Windows is a bit of a pain, especially automated ones.

**Comment by Sampsca** [comment]
@CounterPillow 
<blockquote>For Windows, you may have a point</blockquote>
And Windows, according to which statistics you look at, may constitute upwards of 90% of desktops/laptops.

I'm not *necessarily* saying that compiled binaries *have* to be included in the Git repo, but there definitely should be an **official** download for them somewhere...

**Comment by seamlik** [comment]
Since the developers added the release tag, this issue shall be closed now. Thanks for the quick response!
