### ISSUE TITLE
patch: libzopfli distributed compression

### ISSUE THREAD

**Issue by pdknsk** [google/zopfli#79]
I have a custom PNG optimiser for large files, which uses `libzopfli` for deflate compression. To improve speed, image data is split into chunks, and compression run on multiple cores. This works very well, scales perfectly, and causes only a negligible size increase.

I'm attaching a patch here for anyone interested, or perhaps to be included into `libzopfli` itself. I think it's the least intrusive way to add this, but perhaps not the most elegant, so I'm not submitting a PR.

``` diff
diff --git a/src/zopfli/deflate.c b/src/zopfli/deflate.c
index 4d124f4..7628658 100644
--- a/src/zopfli/deflate.c
+++ b/src/zopfli/deflate.c
@@ -834,18 +834,28 @@ void ZopfliDeflate(const ZopfliOptions* options, int btype, int final,
                    unsigned char* bp, unsigned char** out, size_t* outsize) {
  size_t offset = *outsize;
 #if ZOPFLI_MASTER_BLOCK_SIZE == 0
-  ZopfliDeflatePart(options, btype, final, in, 0, insize, bp, out, outsize);
+  ZopfliDeflatePart(options, btype, final == 1, in, 0, insize, bp, out, outsize);
 #else
   size_t i = 0;
   do {
     int masterfinal = (i + ZOPFLI_MASTER_BLOCK_SIZE >= insize);
-    int final2 = final && masterfinal;
+    int final2 = final == 1 && masterfinal;
     size_t size = masterfinal ? insize - i : ZOPFLI_MASTER_BLOCK_SIZE;
     ZopfliDeflatePart(options, btype, final2,
                       in, i, i + size, bp, out, outsize);
     i += size;
   } while (i < insize);
 #endif
+
+  /* Z_SYNC_FLUSH */
+  if (final == 2) {
+    AddBits(0, 3, bp, out, outsize);
+    ZOPFLI_APPEND_DATA(0, out, outsize);
+    ZOPFLI_APPEND_DATA(0, out, outsize);
+    ZOPFLI_APPEND_DATA(0xFF, out, outsize);
+    ZOPFLI_APPEND_DATA(0xFF, out, outsize);
+  }
+
   if (options->verbose) {
     fprintf(stderr,
             "Original Size: %lu, Deflate: %lu, Compression: %f%% Removed\n",
```

To use this, call `ZopfliDeflate` with `1` passed for `final` on the last chunk, and `2` on all other chunks.

PS. The documentation from the zlib manual.

> If the parameter flush is set to Z_SYNC_FLUSH, all pending output is flushed to the output buffer and the output is aligned on a byte boundary, so that the decompressor can get all input data available so far. [...] This completes the current deflate block and follows it with an empty stored block that is three bits plus filler bits to the next byte, followed by four bytes (00 00 ff ff).

**Comment by alphaonex86** [comment]
Any change on compression ratio? Change on performance?

**Comment by Hello71** [comment]
doesn't pigz already do this

**Comment by alphaonex86** [comment]
But I use zopfli

**Comment by alphaonex86** [comment]
And I use png, pigz don't support png

**Comment by pdknsk** [comment]
I split on 1MB chunks (at scanline boundaries) and the compression ratio
hit is really low, way below 0.1% with the files I benchmarked with. As for
performance, it scales pretty much perfectly with the number of cores.

**Comment by alphaonex86** [comment]
I imagine event better with OpenCL

**Comment by CounterPillow** [comment]
@alphaonex86 no, LZ77 and friends don't translate well to OpenCL or any architecture like it.

**Comment by Jesin** [comment]
Zopfli already does "block splitting". Does that provide a natural way to parallelize the rest of the processing, or is that something else?
