### ISSUE TITLE
gzip_container.c contains sample code from the RFC without any attribution

### ISSUE THREAD

**Issue by julian-klode** [google/zopfli#88]
The CRC code used in gzip_container.c comes almost directly from the RFC 1952, except for the naming conventions and some additional consting. Even the comments are copied.

The RFC 1952 has the following license:

"Permission is granted to copy and distribute this document for any
   purpose and without charge, including translations into other
   languages and incorporation into compilations, provided that the
   copyright notice and this notice are preserved, and that any
   substantive changes or deletions from the original are clearly
   marked."

and copyright
   Copyright (c) 1996 L. Peter Deutsch

There does not appear to be any exception for code anywhere, as such the code must likely be considered non-free and incompatible with the Apache license.

In any case, the file also does not consist of code solely owned by Google, AFAICT.

**Comment by lvandeve** [comment]
Thank you for pointing this out. This was not intended.

As a matter of fact, the CRC code had to be updated to make it compatible with multithreading, so it's changed to a lookup table now.

Please let me know if you have more concerns.
