### ISSUE TITLE
zopfli-1.0.1 tag is not an annotated tag

### ISSUE THREAD

**Issue by CounterPillow** [google/zopfli#90]
Apparently, the zopfli-1.0.1 tag is not properly picked up by `git describe` due to not being an annotated tag, which may trip some packaging scripts. The snippet below demonstrates how this discrepancy occurs even in a freshly cloned git repository:

```
✓ fratti@archbook /tmp $ git clone https://github.com/google/zopfli.git
Cloning into 'zopfli'...
remote: Counting objects: 385, done.
remote: Total 385 (delta 0), reused 0 (delta 0), pack-reused 385
Receiving objects: 100% (385/385), 254.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (215/215), done.
Checking connectivity... done.
✓ fratti@archbook /tmp $ cd zopfli/
✓ fratti@archbook /tmp/zopfli $ git tag --list
zopfli-1.0.0
zopfli-1.0.1
✓ fratti@archbook /tmp/zopfli $ git describe
zopfli-1.0.0-49-g0aa5474
✓ fratti@archbook /tmp/zopfli $ git describe --tags
zopfli-1.0.1-9-g0aa5474
```

Essentially, you forgot the `-a` in `git tag -a zopfli-1.0.1 89cf773`, creating a lightweight instead of an annotated tag, which is usually meant to be used for temporary tags.

**Comment by lvandeve** [comment]
I would recommend using the latest commit. A new tag might be an option.

What kind of packaging systems are having problems? How would the tag best be created? Any changes in the makefile needed?

Thank you.

**Comment by CounterPillow** [comment]
>What kind of packaging systems are having problems?

The package in question [(zopfli-git and friends)](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zopfli-git) in the AUR is using the latest git, but the locally displayed package version that the user sees when he installs it will be misleading as `git describe` ignores the non-annotated tag.

If a user builds the package (which, for AUR packages, is the norm to do if they want to install a package), the PKGBUILD will determine the appropriate version string to set for the package with the pkgver() function, in this case based upon `git describe`. Since, at the moment, this shows `zopfli-1.0.0-` even though it uses the latest git HEAD, this can be confusing.

>How would the tag best be created?

As described, for tagging releases, annotated tags would probably make more sense, since this is also what utilities such as `git describe` expect. I can't say much about when it would make sense to tag something as a new release since all I do is maintain the packaging script for the -git version of it.

>Any changes in the makefile needed?

Related to tags, no. Just having the zopfli-1.0.1 tag replaced by an annotated tag on the same commit would completely suffice to resolve this issue, as then automated packaging systems such as this one have `git describe` work as expected.

**Comment by eli-schwartz** [comment]
@CounterPillow I just used modified the PKGBUILD to use `git describe --long --tags`

**Comment by CounterPillow** [comment]
@eli-schwartz obviously that works, but the core issue is that the git repo uses git tags the wrong way, and it should be fixed there.

**Comment by CounterPillow** [comment]
In order to fix this, all you need is to replace the lightweight tag with an annotated one (like `zopfli-1.0.0` is); you can do this with the following command:

    git tag -a -f zopfli-1.0.1 89cf773

You can then push this without needing a force-push, since the annotated tag builds on top of the lightweight tag.

**Comment by eighthave** [comment]
How about tagging a new release? looks like there has been a lot of work done since the 1.0.1 release.  Then we can update the Debian package easily.

**Comment by dvzrv** [comment]
Hi!
I'm currently maintaining zopfli as a package on Arch Linux.
It would be great, if you could tag a new release and thereby close [many of the issues around the build system](#143).

I currently have to jump through hoops to get a shared library packaged and it would be very much appreciated, if you could release all the changes in a new version.

**Comment by lvandeve** [comment]
I've updated the version number to 1.0.3, marked a release in github, and tried git tag with -a. Let me know if there's anything more I can do to improve this.

Thanks for maintaining the package!

**Comment by dvzrv** [comment]
@lvandeve thanks! This works for me and I've already packaged it :)
