### ISSUE TITLE
mingw64 GCC 5.3 and linux GCC 4.8 - different results

### ISSUE THREAD

**Issue by MrKrzYch00** [google/zopfli#95]
I found an issue with Zopfli (the same behavior happens in my fork) if anybody is interested.

When I compile it using mingw64 GCC 5.3 in MSYS2 (doesn't matter if it's x86 or x64 version, also O0 doesn't make any difference as well) the Windows' binary produces different block slit points and also the progress of iterations progresses differently (when I pass exact same block split points in my fork) than it does with Linux' version compiled with GCC 4.8.x.

Not sure if it's some kind of bug in GCC 4.8.x or regression in GCC 5.3. Also I'm not sure which one provides VALID compilation. Though I know for sure that with older toolchains I used prior to MSYS2 there were no differences.

Example of GCC 5.3 split points produced: 2882 17106 18913 (hex: b42 42d2 49e1)
Example of GCC 4.8 split points produced: 2853 17304 18923 (hex: b25 4398 49eb)

So far I can't figure if there is anything in the code that can be altered since even after enabling all possible warnings and trying code changes to make everything nice according to them, nothing helps.

So if anybody has any more intel, this could be a nice lesson. :)

On a side note. On ARMv7 device (Odroid U3) running my fork I got "ZopfliVerifyLenDist: Assertion `data[pos - dist + i] == data[pos + i]' failed." once. Not sure if it has anything to do with GCC 4.8.x or it's just that some of switches in my fork don't play along with each other on certain data (--brotli --lazy while certain static block split points were passed with --cbs command).

**Comment by JayXon** [comment]
duplicate: https://github.com/google/zopfli/issues/20

**Comment by MrKrzYch00** [comment]
Hmm, interesting. So it should have something to do with double precision... Well changing all floats and doubles to long doubles didn't help either, and GCC 4.8 does provide same results on both ARMv7 and Core i7 (linux/virtualbox), while GCC 5.3 works differently on Core i7 than mentioned both cpus (windows host).

Seems like the produced assembly just does something unexpected either in 4.8 or 5.3 version...

**Comment by MrKrzYch00** [comment]
Accordin to all my EDITs in previous comment, this bug is unrelated to #20, since the bug exist in ZopfliLengthLimitedCodeLengths or in any of its sub-procedures and neither of those do floating point operations.

**Comment by MrKrzYch00** [comment]
This makes zopfli use ascending sorting order when weights are equal instead of reverse which is occuring by default on GCC 5.3.

static int LeafComparator(const void* a, const void* b) {
  const Node *aa = ((const Node*)a);
  const Node *bb = ((const Node*)b);
  if(aa->weight < bb->weight)
   return -1;
  else if(aa->weight > bb->weight)
   return 1;
  else if(aa->count < bb->count)
   return -1;
  else if(aa->count > bb->count)
   return 1;
  else
   return 0;
}

**Comment by jibsen** [comment]
Nice detective work there, @MrKrzYch00.

**Comment by MrKrzYch00** [comment]
Thanks, took a while to figure it out... it's also good to learn that one should really pay attention when relying on qsort. If it differs from compiler to compiler with it's default behavior then it's unstable sorter leading in turn to undefined behavior in rest of the code. :)

**Comment by jibsen** [comment]
The standard does not require qsort to be stable (C11 7.22.5.2p4).

**Comment by MrKrzYch00** [comment]
However, some sort of a warning during compile time could be issued when comparing bigger structures/arrays and the checker is considered too simple, to safe time on debugging later. :)

**Comment by MrKrzYch00** [comment]
OK, here are some tests:
http://virtual.4my.eu/Zopfli%20KrzYmod/tests/multimode.txt

rc means that reverse counting as per GCC 5.3 is used, otherwise GCC 4.8 behavior
ohh means optimized huffman headers are used: https://github.com/frkay/zopfli/commit/9501b29d0dacc8b8efb18ae01733b2768dd40b62
brotli means: https://github.com/MegaByte/zopfli/commit/e6f97e875c1625d835d957c61ee0eb9f988d1f11
lazy is lazy matching.

All last split points are recompressed as shown in the example, as my fork has such feature. For summary scroll the the most bottom.

**Comment by MrKrzYch00** [comment]
Fixed with: https://github.com/google/zopfli/commit/37f6da6ec1f8353a438b5543709207d54476630f
