### ISSUE TITLE
Segmentation fault with keepchunks on certain png

### ISSUE THREAD

**Issue by haarp** [google/zopfli#98]
Here's a file that consistenly causes segfaults in zopflipng when keepchunks is enabled (it does not matter what it is set to, as long as it's enabled):

![bridge-background](https://cloud.githubusercontent.com/assets/781030/14049796/d97705cc-f2b7-11e5-9bab-543246bef606.png)

**Comment by haarp** [comment]
Hmm, GIT master segfaults even without keepchunks

**Comment by lvandeve** [comment]
Thanks for the report. It's now already fixed to work without keepchunks. A second fix to make it work with keepchunks too will follow soon.

**Comment by lvandeve** [comment]
It should be fixed now with keepchunks as well.

**Comment by haarp** [comment]
Sweet, thanks!
